version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "80:80"
    networks:
      - wp-net 

networks:
  wp-net:
    driver: bridge
